# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRSS_6zXEIKGfaNFa78d9TPffJhXMFkC
"""

from pprint import pprint
scene = {
  "short_description": "A detailed cross-section view of a female breast, highlighting a Stage II tumor in the upper outer quadrant. The image uses a medical neutral color palette, emphasizing anatomical accuracy and clarity for clinical study.",
  "objects": [
    {
      "description": "The internal structure of a female breast, meticulously rendered to show various tissue layers including glandular tissue, fatty tissue, and ducts.",
      "location": "center",
      "relationship": "The central subject",
      "relative_size": "large within frame",
      "shape_and_color": "Muted pinks, creams, and whites",
      "texture": "Smooth",
      "appearance_details": "Highly detailed anatomical rendering",
      "orientation": "vertical"
    },
    {
      "description": "A malignant tumor, approximately 28mm in diameter, positioned within the upper outer quadrant of the breast.",
      "location": "upper-right quadrant",
      "relationship": "Embedded within tissue",
      "relative_size": "medium",
      "shape_and_color": "Darker purple-grey mass",
      "texture": "Dense and granular",
      "appearance_details": "Irregular margins, micro-calcifications",
      "orientation": "irregular"
    }
  ],
  "background_setting": "Sterile white background",
  "lighting": {
    "conditions": "Soft, diffused clinical lighting",
    "direction": "Even distribution",
    "shadows": "Minimal"
  },
  "context": "Medical visualization for breast cancer awareness"
}
print("🩺 Scene Description:")
print(scene["short_description"])
tumor = scene["objects"][1]

print("Tumor Analysis")
print("Location:", tumor["location"])
print("Texture:", tumor["texture"])
print("Visual Clues:", tumor["appearance_details"])

def interpret_tumor(tumor):
    if "Irregular" in tumor["appearance_details"]:
        return "⚠️ Irregular margins suggest invasive tumor behavior."
    return "Tumor characteristics appear benign."

print(interpret_tumor(tumor))

report = f"""
AI-Assisted Breast Cancer Insight Report
----------------------------------------
Tumor Location: {tumor['location']}
Tumor Size Category: {tumor['relative_size']}
Key Risk Indicator: {tumor['appearance_details']}
"""

print(report)

